# Generated by Django 3.0.7 on 2020-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='massage',
            new_name='message',
        ),
    ]
